/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.simplemontagemaker;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.bramp.ffmpeg.FFmpeg;
import net.bramp.ffmpeg.FFprobe;

/**
 *
 * @author Omer
 */
public class smm extends javax.swing.JFrame {

    static boolean isOpenComp;
    static boolean isOpenTrim;
    static boolean isOpenComb;

    public static boolean isIsOpenComp() {
        return isOpenComp;
    }

    public static void setIsOpenComp(boolean isOpenComp) {
        smm.isOpenComp = isOpenComp;
    }

    public static void setIsOpenTrim(boolean isOpenTrim) {
        smm.isOpenTrim = isOpenTrim;
    }

    public static void setIsOpenComb(boolean isOpenComb) {
        smm.isOpenComb = isOpenComb;
    }

    public static boolean isIsOpenTrim() {
        return isOpenTrim;
    }

    public static boolean isIsOpenComb() {
        return isOpenComb;
    }

    /**
     * Creates new form smm
     */
    public smm() {
        Settings.init();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cut_jButton1 = new javax.swing.JButton();
        compress_jButton2 = new javax.swing.JButton();
        combiner_jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Montage Maker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cut_jButton1.setBackground(new java.awt.Color(204, 255, 255));
        cut_jButton1.setText("Trimmer Menu");
        cut_jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cut_jButton1MouseClicked(evt);
            }
        });

        compress_jButton2.setBackground(new java.awt.Color(204, 255, 255));
        compress_jButton2.setText("Compress Menu");
        compress_jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compress_jButton2MouseClicked(evt);
            }
        });

        combiner_jButton3.setBackground(new java.awt.Color(204, 255, 255));
        combiner_jButton3.setText("Combiner Menu");
        combiner_jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combiner_jButton3MouseClicked(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        label1.setText("Simple Montage Maker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combiner_jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compress_jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(cut_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(compress_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cut_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combiner_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compress_jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compress_jButton2MouseClicked
        // TODO add your handling code here:
        if (!isOpenComp) {
            Compressor_Menu.main(null);
            isOpenComp = true;
        } else {
            // dialog is already open
            JOptionPane.showMessageDialog(this, "File Compressor is already open!");
//        Compressor_Menu.ShowMe();
        }

    }//GEN-LAST:event_compress_jButton2MouseClicked

    private void cut_jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cut_jButton1MouseClicked
        // TODO add your handling code here:
        if (!isOpenTrim) {
            Trimmer_Menu.main(null);
            isOpenTrim = true;
        } else {
            // dialog is already open
            JOptionPane.showMessageDialog(this, "File Trimmer is already open!");

//        Compressor_Menu.ShowMe();
        }


    }//GEN-LAST:event_cut_jButton1MouseClicked

    private void combiner_jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combiner_jButton3MouseClicked
        // TODO add your handling code here:
        if (!isOpenComb) {
            Combiner_Menu.main(null);
            isOpenComb = true;
        } else {
            // dialog is already open
            JOptionPane.showMessageDialog(this, "File Combiner is already open!");
//        Compressor_Menu.ShowMe();
        }


    }//GEN-LAST:event_combiner_jButton3MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (!Settings.fList.isEmpty()) {
            int ans = JOptionPane.showConfirmDialog(new JFrame(), "Some proccesses are still working, exiting now might cause a currputed files and will cancel the action\n are you sure you wan to exit", "Warning!",
                    JOptionPane.YES_NO_OPTION);
            if (ans == 0) {
                Settings.exit();

            }

        } else {
            Settings.exit();

        }

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combiner_jButton3;
    private javax.swing.JButton compress_jButton2;
    private javax.swing.JButton cut_jButton1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
